version: '3'

networks:
  default:
    driver: bridge

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "80:80"
    networks:
      - default
    depends_on:
      - db
    volumes:
      - "../app:/var/www/app"
      - "./conf/nginx:/etc/nginx/sites-available"

  db:
    image: mysql:latest
    networks:
      - default
    ports:
      - "3336:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii-template-db
    volumes:
      - "./database:/var/lib/mysql"